### POST request to hit book-appointment api
POST http://localhost:8080/api/appointments/book
Content-Type: application/json

{
  "departmentCode": "CARDIO",
  "doctorId": "some-doctor-uuid",
  "slotId": "some-slot-uuid"
}
###